In [1]:
import glob
import numpy as np
from collections import deque
from tqdm import tqdm

In [2]:
# glob for all saved images in their individual 'imgs_2016...' folders.
originals = glob.glob('./imgs_2016*/*.jpg')
for folder in originals:
    print folder

In [5]:
len(originals)

2512

In [6]:
# glob for all saved label_arrays in their individual 'imgs_2016...' folders.
originals = glob.glob('./imgs_2016*/label_array_ORIGINALS.npz')
for npz in originals:
    print npz

./imgs_20161024_201843/label_array_ORIGINALS.npz
./imgs_20161024_203956/label_array_ORIGINALS.npz
./imgs_20161024_205205/label_array_ORIGINALS.npz
./imgs_20161024_210342/label_array_ORIGINALS.npz
./imgs_20161024_213033/label_array_ORIGINALS.npz
./imgs_20161024_213758/label_array_ORIGINALS.npz
./imgs_20161024_214826/label_array_ORIGINALS.npz
./imgs_20161024_215723/label_array_ORIGINALS.npz
./imgs_20161024_220400/label_array_ORIGINALS.npz
./imgs_20161024_221046/label_array_ORIGINALS.npz
./imgs_20161024_221817/label_array_ORIGINALS.npz
./imgs_20161024_222638/label_array_ORIGINALS.npz
./imgs_20161024_223408/label_array_ORIGINALS.npz
./imgs_20161024_224114/label_array_ORIGINALS.npz
./imgs_20161024_224955/label_array_ORIGINALS.npz
./imgs_20161024_225859/label_array_ORIGINALS.npz


In [7]:
len(originals)

16


In [45]:
# label_array starts off as one row of zeros. As items are added, they are vstacked from below.
label_array = np.zeros((1, 3), 'float')
n=3

# rows_updated = 0
# success_count = 0


training_data_labels = glob.glob('./images/imgs_2016*/label_array_ORIGINALS.npz')

for single_npz in tqdm(training_data_labels):

    with np.load(single_npz) as data:
        
        # ORIGINAL LABELS
        labels = data.f.train_labels
        original_labels_shape = labels.shape
        print 'Original Labels dims: ', labels.shape
        
        array_list = labels.tolist()
#         print len(array_list)
        
        # This 'final' empty list will only be used when augment=False
        final = []

        # For each original label...
        for row in array_list:

####        if augment: (THIS IS THE PATH FOLLOWED IF augment=True)
            # make temporary deque()
            temp_list = []

            # for self.n times, add ORIGINAL LABEL to deque
            for i in xrange(n):
                temp_list.append(row)

            # for self.n times, add FLIPPED LABEL to deque
            for i in xrange(n):

                # Forward-Left becomes Forward-Right, append
                if row[0] == 1:
                    temp_list.append([0.0, 1.0, 0.0])

                # Forward-Right becomes Forward-Left, append
                elif row[1] == 1:
                    temp_list.append([1.0, 0.0, 0.0])

                # Forward remains as Forward, append
                elif row[2] == 1:
                    temp_list.append([0.0, 0.0, 1.0])
                    continue

            temp_deque = deque(temp_list)



# # POOR MAN'S UNIT TEST
#             # Forward stays Forward
#             if temp_list[0:3] == [[0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0]] \
#                 and temp_list[3:6] == [[0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0]] :
#                 success_count += 1
                
#             # Right goes to Left
#             elif temp_list[0:3] == [[0.0, 1.0, 0.0], [0.0, 1.0, 0.0], [0.0, 1.0, 0.0]] \
#                 and temp_list[3:6] == [[1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0]] :
#                 success_count += 1
            
#             # Left goes to Right
#             elif temp_list[0:3] == [[1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0]] \
#                 and temp_list[3:6] == [[0.0, 1.0, 0.0], [0.0, 1.0, 0.0], [0.0, 1.0, 0.0]] :
#                 success_count += 1
        
#             rows_updated += 1
#             print 'temp_list',temp_list
#             print temp_deque
#             print ''
# print 'Total # rows updated:', rows_updated
# print 'Total # successes:', success_count
# print 'Success rate:', float(success_count/rows_updated)*100, '%'
# # END: POOR MAN'S UNIT TEST
            
#             print len(temp_deque)
#             print temp_deque.popleft()
#             print temp_deque.pop()
#             print len(temp_deque)



            # vstack to label_array, popping left and right, for as long as temp_deque has something in it to pop.
            for i in xrange(n):
                left  = temp_deque.popleft()
                right = temp_deque.pop()
                label_array = np.vstack((label_array, left))
                label_array = np.vstack((label_array, right))


print type(label_array)                
print 'Final label_array dims:', label_array.shape
print 'Final label_array:', label_array
            
            

 22%|██▏       | 7/32 [00:00<00:00, 53.65it/s]

Original Labels dims:  (140, 3)
Original Labels dims:  (150, 3)
Original Labels dims:  (153, 3)
Original Labels dims:  (155, 3)
Original Labels dims:  (157, 3)
Original Labels dims:  (158, 3)
Original Labels dims:  (155, 3)
Original Labels dims:  (160, 3)
Original Labels dims:  (164, 3)
Original Labels dims:  (157, 3)


 44%|████▍     | 14/32 [00:00<00:00, 34.49it/s]

Original Labels dims:  (160, 3)
Original Labels dims:  (161, 3)
Original Labels dims:  (160, 3)
Original Labels dims:  (160, 3)
Original Labels dims:  (162, 3)


 53%|█████▎    | 17/32 [00:00<00:00, 26.78it/s]

Original Labels dims:  (160, 3)
Original Labels dims:  (161, 3)
Original Labels dims:  (166, 3)
Original Labels dims:  (170, 3)


 62%|██████▎   | 20/32 [00:00<00:00, 20.89it/s]

Original Labels dims:  (163, 3)
Original Labels dims:  (161, 3)
Original Labels dims:  (160, 3)


 75%|███████▌  | 24/32 [00:01<00:00, 15.21it/s]

Original Labels dims:  (168, 3)
Original Labels dims:  (167, 3)
Original Labels dims:  (170, 3)


 81%|████████▏ | 26/32 [00:01<00:00, 12.59it/s]

Original Labels dims:  (170, 3)
Original Labels dims:  (170, 3)


 88%|████████▊ | 28/32 [00:01<00:00,  8.30it/s]

Original Labels dims:  (171, 3)
Original Labels dims:  (170, 3)


 94%|█████████▍| 30/32 [00:02<00:00,  8.29it/s]

Original Labels dims:  (170, 3)
Original Labels dims:  (170, 3)


100%|██████████| 32/32 [00:02<00:00,  6.82it/s]

Original Labels dims:  (175, 3)
<type 'numpy.ndarray'>
Final label_array dims: (31165, 3)
Final label_array: [[ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 ..., 
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]
